name=ESPHttpxClient
version=0.1.0b
author=D. Xavier <47609623+davirxavier@users.noreply.github.com>
maintainer=D. Xavier <47609623+davirxavier@users.noreply.github.com>
sentence=Async HTTP/HTTPS client for ESP32 built on esp_tls.
paragraph=A fully event-driven state machine designed for long-lived connections, chunked transfer encoding, and multipart streaming.
category=Communication
url=https://github.com/davirxavier/esp-httpx-client
architectures=esp32
includes=ESPHTTPxClient.h